/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface DaiInterface extends Interface {
  functions: {
    DOMAIN_SEPARATOR: TypedFunctionDescription<{ encode([]: []): string }>;

    PERMIT_TYPEHASH: TypedFunctionDescription<{ encode([]: []): string }>;

    allowance: TypedFunctionDescription<{
      encode([,]: [string, string]): string;
    }>;

    balanceOf: TypedFunctionDescription<{ encode([]: [string]): string }>;

    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    name: TypedFunctionDescription<{ encode([]: []): string }>;

    nonces: TypedFunctionDescription<{ encode([]: [string]): string }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    version: TypedFunctionDescription<{ encode([]: []): string }>;

    wards: TypedFunctionDescription<{ encode([]: [string]): string }>;

    rely: TypedFunctionDescription<{ encode([guy]: [string]): string }>;

    deny: TypedFunctionDescription<{ encode([guy]: [string]): string }>;

    transfer: TypedFunctionDescription<{
      encode([dst, wad]: [string, BigNumberish]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([src, dst, wad]: [string, string, BigNumberish]): string;
    }>;

    mint: TypedFunctionDescription<{
      encode([usr, wad]: [string, BigNumberish]): string;
    }>;

    burn: TypedFunctionDescription<{
      encode([usr, wad]: [string, BigNumberish]): string;
    }>;

    approve: TypedFunctionDescription<{
      encode([usr, wad]: [string, BigNumberish]): string;
    }>;

    push: TypedFunctionDescription<{
      encode([usr, wad]: [string, BigNumberish]): string;
    }>;

    pull: TypedFunctionDescription<{
      encode([usr, wad]: [string, BigNumberish]): string;
    }>;

    move: TypedFunctionDescription<{
      encode([src, dst, wad]: [string, string, BigNumberish]): string;
    }>;

    permit: TypedFunctionDescription<{
      encode([holder, spender, nonce, expiry, allowed, v, r, s]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        boolean,
        BigNumberish,
        Arrayish,
        Arrayish
      ]): string;
    }>;
  };

  events: {
    Approval: TypedEventDescription<{
      encodeTopics([src, guy, wad]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    Transfer: TypedEventDescription<{
      encodeTopics([src, dst, wad]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;
  };
}

export class Dai extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Dai;
  attach(addressOrName: string): Dai;
  deployed(): Promise<Dai>;

  on(event: EventFilter | string, listener: Listener): Dai;
  once(event: EventFilter | string, listener: Listener): Dai;
  addListener(eventName: EventFilter | string, listener: Listener): Dai;
  removeAllListeners(eventName: EventFilter | string): Dai;
  removeListener(eventName: any, listener: Listener): Dai;

  interface: DaiInterface;

  functions: {
    DOMAIN_SEPARATOR(): Promise<string>;

    PERMIT_TYPEHASH(): Promise<string>;

    allowance(arg0: string, arg1: string): Promise<BigNumber>;

    balanceOf(arg0: string): Promise<BigNumber>;

    decimals(): Promise<number>;

    name(): Promise<string>;

    nonces(arg0: string): Promise<BigNumber>;

    symbol(): Promise<string>;

    totalSupply(): Promise<BigNumber>;

    version(): Promise<string>;

    wards(arg0: string): Promise<BigNumber>;

    rely(
      guy: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deny(
      guy: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transfer(
      dst: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      src: string,
      dst: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    mint(
      usr: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    burn(
      usr: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    approve(
      usr: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    push(
      usr: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    pull(
      usr: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    move(
      src: string,
      dst: string,
      wad: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    permit(
      holder: string,
      spender: string,
      nonce: BigNumberish,
      expiry: BigNumberish,
      allowed: boolean,
      v: BigNumberish,
      r: Arrayish,
      s: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  DOMAIN_SEPARATOR(): Promise<string>;

  PERMIT_TYPEHASH(): Promise<string>;

  allowance(arg0: string, arg1: string): Promise<BigNumber>;

  balanceOf(arg0: string): Promise<BigNumber>;

  decimals(): Promise<number>;

  name(): Promise<string>;

  nonces(arg0: string): Promise<BigNumber>;

  symbol(): Promise<string>;

  totalSupply(): Promise<BigNumber>;

  version(): Promise<string>;

  wards(arg0: string): Promise<BigNumber>;

  rely(
    guy: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deny(
    guy: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transfer(
    dst: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    src: string,
    dst: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  mint(
    usr: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  burn(
    usr: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  approve(
    usr: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  push(
    usr: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  pull(
    usr: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  move(
    src: string,
    dst: string,
    wad: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  permit(
    holder: string,
    spender: string,
    nonce: BigNumberish,
    expiry: BigNumberish,
    allowed: boolean,
    v: BigNumberish,
    r: Arrayish,
    s: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    Approval(src: string | null, guy: string | null, wad: null): EventFilter;

    Transfer(src: string | null, dst: string | null, wad: null): EventFilter;
  };

  estimate: {
    DOMAIN_SEPARATOR(): Promise<BigNumber>;

    PERMIT_TYPEHASH(): Promise<BigNumber>;

    allowance(arg0: string, arg1: string): Promise<BigNumber>;

    balanceOf(arg0: string): Promise<BigNumber>;

    decimals(): Promise<BigNumber>;

    name(): Promise<BigNumber>;

    nonces(arg0: string): Promise<BigNumber>;

    symbol(): Promise<BigNumber>;

    totalSupply(): Promise<BigNumber>;

    version(): Promise<BigNumber>;

    wards(arg0: string): Promise<BigNumber>;

    rely(guy: string): Promise<BigNumber>;

    deny(guy: string): Promise<BigNumber>;

    transfer(dst: string, wad: BigNumberish): Promise<BigNumber>;

    transferFrom(
      src: string,
      dst: string,
      wad: BigNumberish
    ): Promise<BigNumber>;

    mint(usr: string, wad: BigNumberish): Promise<BigNumber>;

    burn(usr: string, wad: BigNumberish): Promise<BigNumber>;

    approve(usr: string, wad: BigNumberish): Promise<BigNumber>;

    push(usr: string, wad: BigNumberish): Promise<BigNumber>;

    pull(usr: string, wad: BigNumberish): Promise<BigNumber>;

    move(src: string, dst: string, wad: BigNumberish): Promise<BigNumber>;

    permit(
      holder: string,
      spender: string,
      nonce: BigNumberish,
      expiry: BigNumberish,
      allowed: boolean,
      v: BigNumberish,
      r: Arrayish,
      s: Arrayish
    ): Promise<BigNumber>;
  };
}
