/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { DSAuthority } from "./DSAuthority";

export class DSAuthorityFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DSAuthority {
    return new Contract(address, _abi, signerOrProvider) as DSAuthority;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "src",
        type: "address"
      },
      {
        internalType: "address",
        name: "dst",
        type: "address"
      },
      {
        internalType: "bytes4",
        name: "sig",
        type: "bytes4"
      }
    ],
    name: "canCall",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
