/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface DSTokenLikeInterface extends Interface {
  functions: {
    mint: TypedFunctionDescription<{
      encode([,]: [string, BigNumberish]): string;
    }>;

    burn: TypedFunctionDescription<{
      encode([,]: [string, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class DSTokenLike extends Contract {
  connect(signerOrProvider: Signer | Provider | string): DSTokenLike;
  attach(addressOrName: string): DSTokenLike;
  deployed(): Promise<DSTokenLike>;

  on(event: EventFilter | string, listener: Listener): DSTokenLike;
  once(event: EventFilter | string, listener: Listener): DSTokenLike;
  addListener(eventName: EventFilter | string, listener: Listener): DSTokenLike;
  removeAllListeners(eventName: EventFilter | string): DSTokenLike;
  removeListener(eventName: any, listener: Listener): DSTokenLike;

  interface: DSTokenLikeInterface;

  functions: {
    mint(
      arg0: string,
      arg1: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    burn(
      arg0: string,
      arg1: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  mint(
    arg0: string,
    arg1: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  burn(
    arg0: string,
    arg1: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    mint(arg0: string, arg1: BigNumberish): Promise<BigNumber>;

    burn(arg0: string, arg1: BigNumberish): Promise<BigNumber>;
  };
}
