/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IDaiBackstopSyndicate } from "./IDaiBackstopSyndicate";

export class IDaiBackstopSyndicateFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDaiBackstopSyndicate {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDaiBackstopSyndicate;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "auctionId",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "mkrAsk",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "daiBid",
        type: "uint256"
      }
    ],
    name: "AuctionEntered",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "auctionId",
        type: "uint256"
      }
    ],
    name: "AuctionFinalized",
    type: "event"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "daiAmount",
        type: "uint256"
      }
    ],
    name: "enlist",
    outputs: [
      {
        internalType: "uint256",
        name: "backstopTokensMinted",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "backstopTokenAmount",
        type: "uint256"
      }
    ],
    name: "defect",
    outputs: [
      {
        internalType: "uint256",
        name: "daiRedeemed",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "mkrRedeemed",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "auctionId",
        type: "uint256"
      }
    ],
    name: "enterAuction",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "auctionId",
        type: "uint256"
      }
    ],
    name: "finalizeAuction",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [],
    name: "ceaseFire",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getStatus",
    outputs: [
      {
        internalType: "enum IDaiBackstopSyndicate.Status",
        name: "status",
        type: "uint8"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getActiveAuctions",
    outputs: [
      {
        internalType: "uint256[]",
        name: "activeAuctions",
        type: "uint256[]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
