/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IFlopperInterface extends Interface {
  functions: {
    wards: TypedFunctionDescription<{ encode([]: [string]): string }>;

    rely: TypedFunctionDescription<{ encode([usr]: [string]): string }>;

    deny: TypedFunctionDescription<{ encode([usr]: [string]): string }>;

    bids: TypedFunctionDescription<{ encode([]: [BigNumberish]): string }>;

    vat: TypedFunctionDescription<{ encode([]: []): string }>;

    gem: TypedFunctionDescription<{ encode([]: []): string }>;

    ONE: TypedFunctionDescription<{ encode([]: []): string }>;

    beg: TypedFunctionDescription<{ encode([]: []): string }>;

    pad: TypedFunctionDescription<{ encode([]: []): string }>;

    ttl: TypedFunctionDescription<{ encode([]: []): string }>;

    tau: TypedFunctionDescription<{ encode([]: []): string }>;

    kicks: TypedFunctionDescription<{ encode([]: []): string }>;

    live: TypedFunctionDescription<{ encode([]: []): string }>;

    vow: TypedFunctionDescription<{ encode([]: []): string }>;

    file: TypedFunctionDescription<{
      encode([what, data]: [Arrayish, BigNumberish]): string;
    }>;

    kick: TypedFunctionDescription<{
      encode([gal, lot, bid]: [string, BigNumberish, BigNumberish]): string;
    }>;

    tick: TypedFunctionDescription<{ encode([id]: [BigNumberish]): string }>;

    dent: TypedFunctionDescription<{
      encode([id, lot, bid]: [
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    deal: TypedFunctionDescription<{ encode([id]: [BigNumberish]): string }>;

    cage: TypedFunctionDescription<{ encode([]: []): string }>;

    yank: TypedFunctionDescription<{ encode([id]: [BigNumberish]): string }>;
  };

  events: {
    Kick: TypedEventDescription<{
      encodeTopics([id, lot, bid, gal]: [
        null,
        null,
        null,
        string | null
      ]): string[];
    }>;
  };
}

export class IFlopper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IFlopper;
  attach(addressOrName: string): IFlopper;
  deployed(): Promise<IFlopper>;

  on(event: EventFilter | string, listener: Listener): IFlopper;
  once(event: EventFilter | string, listener: Listener): IFlopper;
  addListener(eventName: EventFilter | string, listener: Listener): IFlopper;
  removeAllListeners(eventName: EventFilter | string): IFlopper;
  removeListener(eventName: any, listener: Listener): IFlopper;

  interface: IFlopperInterface;

  functions: {
    wards(arg0: string): Promise<BigNumber>;

    rely(
      usr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deny(
      usr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    bids(
      arg0: BigNumberish
    ): Promise<{
      bid: BigNumber;
      lot: BigNumber;
      guy: string;
      tic: number;
      end: number;
      0: BigNumber;
      1: BigNumber;
      2: string;
      3: number;
      4: number;
    }>;

    vat(): Promise<string>;

    gem(): Promise<string>;

    ONE(): Promise<BigNumber>;

    beg(): Promise<BigNumber>;

    pad(): Promise<BigNumber>;

    ttl(): Promise<number>;

    tau(): Promise<number>;

    kicks(): Promise<BigNumber>;

    live(): Promise<BigNumber>;

    vow(): Promise<string>;

    file(
      what: Arrayish,
      data: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    kick(
      gal: string,
      lot: BigNumberish,
      bid: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    tick(
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    dent(
      id: BigNumberish,
      lot: BigNumberish,
      bid: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deal(
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    cage(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    yank(
      id: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  wards(arg0: string): Promise<BigNumber>;

  rely(
    usr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deny(
    usr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  bids(
    arg0: BigNumberish
  ): Promise<{
    bid: BigNumber;
    lot: BigNumber;
    guy: string;
    tic: number;
    end: number;
    0: BigNumber;
    1: BigNumber;
    2: string;
    3: number;
    4: number;
  }>;

  vat(): Promise<string>;

  gem(): Promise<string>;

  ONE(): Promise<BigNumber>;

  beg(): Promise<BigNumber>;

  pad(): Promise<BigNumber>;

  ttl(): Promise<number>;

  tau(): Promise<number>;

  kicks(): Promise<BigNumber>;

  live(): Promise<BigNumber>;

  vow(): Promise<string>;

  file(
    what: Arrayish,
    data: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  kick(
    gal: string,
    lot: BigNumberish,
    bid: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  tick(
    id: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  dent(
    id: BigNumberish,
    lot: BigNumberish,
    bid: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  deal(
    id: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  cage(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  yank(
    id: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    Kick(id: null, lot: null, bid: null, gal: string | null): EventFilter;
  };

  estimate: {
    wards(arg0: string): Promise<BigNumber>;

    rely(usr: string): Promise<BigNumber>;

    deny(usr: string): Promise<BigNumber>;

    bids(arg0: BigNumberish): Promise<BigNumber>;

    vat(): Promise<BigNumber>;

    gem(): Promise<BigNumber>;

    ONE(): Promise<BigNumber>;

    beg(): Promise<BigNumber>;

    pad(): Promise<BigNumber>;

    ttl(): Promise<BigNumber>;

    tau(): Promise<BigNumber>;

    kicks(): Promise<BigNumber>;

    live(): Promise<BigNumber>;

    vow(): Promise<BigNumber>;

    file(what: Arrayish, data: BigNumberish): Promise<BigNumber>;

    kick(gal: string, lot: BigNumberish, bid: BigNumberish): Promise<BigNumber>;

    tick(id: BigNumberish): Promise<BigNumber>;

    dent(
      id: BigNumberish,
      lot: BigNumberish,
      bid: BigNumberish
    ): Promise<BigNumber>;

    deal(id: BigNumberish): Promise<BigNumber>;

    cage(): Promise<BigNumber>;

    yank(id: BigNumberish): Promise<BigNumber>;
  };
}
