/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IJoinInterface extends Interface {
  functions: {
    join: TypedFunctionDescription<{
      encode([,]: [string, BigNumberish]): string;
    }>;

    exit: TypedFunctionDescription<{
      encode([,]: [string, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IJoin extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IJoin;
  attach(addressOrName: string): IJoin;
  deployed(): Promise<IJoin>;

  on(event: EventFilter | string, listener: Listener): IJoin;
  once(event: EventFilter | string, listener: Listener): IJoin;
  addListener(eventName: EventFilter | string, listener: Listener): IJoin;
  removeAllListeners(eventName: EventFilter | string): IJoin;
  removeListener(eventName: any, listener: Listener): IJoin;

  interface: IJoinInterface;

  functions: {
    join(
      arg0: string,
      arg1: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    exit(
      arg0: string,
      arg1: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  join(
    arg0: string,
    arg1: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  exit(
    arg0: string,
    arg1: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    join(arg0: string, arg1: BigNumberish): Promise<BigNumber>;

    exit(arg0: string, arg1: BigNumberish): Promise<BigNumber>;
  };
}
