/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IVatInterface extends Interface {
  functions: {
    dai: TypedFunctionDescription<{ encode([]: [string]): string }>;

    hope: TypedFunctionDescription<{ encode([]: [string]): string }>;

    move: TypedFunctionDescription<{
      encode([, ,]: [string, string, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IVat extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IVat;
  attach(addressOrName: string): IVat;
  deployed(): Promise<IVat>;

  on(event: EventFilter | string, listener: Listener): IVat;
  once(event: EventFilter | string, listener: Listener): IVat;
  addListener(eventName: EventFilter | string, listener: Listener): IVat;
  removeAllListeners(eventName: EventFilter | string): IVat;
  removeListener(eventName: any, listener: Listener): IVat;

  interface: IVatInterface;

  functions: {
    dai(arg0: string): Promise<BigNumber>;

    hope(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    move(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  dai(arg0: string): Promise<BigNumber>;

  hope(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  move(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    dai(arg0: string): Promise<BigNumber>;

    hope(arg0: string): Promise<BigNumber>;

    move(arg0: string, arg1: string, arg2: BigNumberish): Promise<BigNumber>;
  };
}
