/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IVowInterface extends Interface {
  functions: {
    wait: TypedFunctionDescription<{ encode([]: []): string }>;

    dump: TypedFunctionDescription<{ encode([]: []): string }>;

    sump: TypedFunctionDescription<{ encode([]: []): string }>;

    flop: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class IVow extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IVow;
  attach(addressOrName: string): IVow;
  deployed(): Promise<IVow>;

  on(event: EventFilter | string, listener: Listener): IVow;
  once(event: EventFilter | string, listener: Listener): IVow;
  addListener(eventName: EventFilter | string, listener: Listener): IVow;
  removeAllListeners(eventName: EventFilter | string): IVow;
  removeListener(eventName: any, listener: Listener): IVow;

  interface: IVowInterface;

  functions: {
    wait(): Promise<BigNumber>;

    dump(): Promise<BigNumber>;

    sump(): Promise<BigNumber>;

    flop(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };

  wait(): Promise<BigNumber>;

  dump(): Promise<BigNumber>;

  sump(): Promise<BigNumber>;

  flop(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    wait(): Promise<BigNumber>;

    dump(): Promise<BigNumber>;

    sump(): Promise<BigNumber>;

    flop(): Promise<BigNumber>;
  };
}
