/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { MkrAuthority } from "./MkrAuthority";

export class MkrAuthorityFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<MkrAuthority> {
    return super.deploy() as Promise<MkrAuthority>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): MkrAuthority {
    return super.attach(address) as MkrAuthority;
  }
  connect(signer: Signer): MkrAuthorityFactory {
    return super.connect(signer) as MkrAuthorityFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MkrAuthority {
    return new Contract(address, _abi, signerOrProvider) as MkrAuthority;
  }
}

const _abi = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "usr",
        type: "address"
      }
    ],
    name: "LogDeny",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "usr",
        type: "address"
      }
    ],
    name: "LogRely",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newRoot",
        type: "address"
      }
    ],
    name: "LogSetRoot",
    type: "event"
  },
  {
    constant: true,
    inputs: [],
    name: "root",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    name: "wards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address"
      }
    ],
    name: "setRoot",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address"
      }
    ],
    name: "rely",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address"
      }
    ],
    name: "deny",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "src",
        type: "address"
      },
      {
        internalType: "address",
        name: "",
        type: "address"
      },
      {
        internalType: "bytes4",
        name: "sig",
        type: "bytes4"
      }
    ],
    name: "canCall",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610396806100326000396000f3fe608060405234801561001057600080fd5b50600436106100615760003560e01c80623ba1ed1461006657806365fae35e1461008e5780639c52a7f1146100b4578063b7009613146100da578063bf353dbb1461012f578063ebf0c71714610167575b600080fd5b61008c6004803603602081101561007c57600080fd5b50356001600160a01b031661018b565b005b61008c600480360360208110156100a457600080fd5b50356001600160a01b03166101ea565b61008c600480360360208110156100ca57600080fd5b50356001600160a01b0316610248565b61011b600480360360608110156100f057600080fd5b5080356001600160a01b0390811691602081013590911690604001356001600160e01b0319166102a3565b604080519115158252519081900360200190f35b6101556004803603602081101561014557600080fd5b50356001600160a01b0316610340565b60408051918252519081900360200190f35b61016f610352565b604080516001600160a01b039092168252519081900360200190f35b6000546001600160a01b031633146101a257600080fd5b600080546001600160a01b0319166001600160a01b038316908117825560405190917f590b975c6c0ad07291052d35e354944ebed986091d40026a932b3b6d122e753c91a250565b6000546001600160a01b0316331461020157600080fd5b6001600160a01b038116600081815260016020819052604080832091909155517fbcea0e0a8da02ca32f79ec827797ef9d9b799f0f530a7015479294f8605f26dc9190a250565b6000546001600160a01b0316331461025f57600080fd5b6001600160a01b038116600081815260016020526040808220829055517f2569dba00999b9a749665fecc99518b00d82fa6179a90d094a04f4c50b952ba19190a250565b60006001600160e01b03198216630852cd8d60e31b14806102d457506001600160e01b03198216632770a7eb60e21b145b806102ec57506000546001600160a01b038581169116145b156102f957506001610339565b6001600160e01b031982166340c10f1960e01b141561033557506001600160a01b03831660009081526001602081905260409091205414610339565b5060005b9392505050565b60016020526000908152604090205481565b6000546001600160a01b03168156fea265627a7a72315820bdbaa2c037ab7169ba22cb0242b397609671025d3ef282e1b0f19375bc1f0a8264736f6c63430005100032";
